// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.testng.annotations.Test;

import java.util.*;

public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Test
  public void login() {
    driver.get("https://www.worldmarket.com/account/login.do");
    driver.manage().window().setSize(new Dimension(1680, 956));
    driver.findElement(By.id("loginEmail")).click();
    driver.findElement(By.id("loginEmail")).sendKeys("a@a.a");
    driver.findElement(By.id("loginPassword")).click();
    driver.findElement(By.id("loginPassword")).sendKeys("123123");
    driver.findElement(By.id("checkoutLoginButton")).click();
    {
      WebElement element = driver.findElement(By.id("checkoutLoginButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ml-csvalidation-error:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".ml-csvalidation-error:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ml-csvalidation-error:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ml-csvalidation-error:nth-child(1)")).click();
    driver.findElement(By.id("forgotPassword")).click();
    driver.findElement(By.id("resetPasswordRadio")).click();
  }
}
